# Plugins that are planned on being removed
[[plugins]]
repository = 'rhysd/accelerated-jk'
mappings = [
  '<Plug>(accelerated_jk_gj)', '<Plug>(accelerated_jk_gk)',
  '<Plug>(accelerated_jk_gj_position', '<Plug>(accelerated_jk_gk_position)',
  '<Plug>(accelerated_jk_j)', '<Plug>(accelerated_jk_k)',
  '<Plug>(accelerated_jk_j_position', '<Plug>(accelerated_jk_k_position)',
]

[[plugins]]
repository = 'NigoroJr/foofile.vim'

  [plugins.commands]
  name = 'FooFile'
  complete = 'customlist,foofile#complete'

  [plugins.commands]
  name = 'FooFileLast'
  complete = 'customlist,foofile#complete'

  [plugins.commands]
  name = 'FooFileDelete'
  complete = 'customlist,foofile#complete'

  [plugins.commands]
  name = 'FooFileSaveAs'
  complete = 'file'

[[plugins]]
repository = 'gcmt/wildfire.vim'
mappings = ['<Plug>(wildfire-water)', '<Plug>(wildfire-fuel)']

[[plugins]]
repository = 'justmao945/vim-clang'
filetypes = ['c', 'cpp']
# Ideally neobundle#is_installed('vim-marching'), but not due to the parsing.
# See vim-clang section in .vimrc for more details.
disabled = """
!exists('g:use_vim_clang') || !g:use_vim_clang \
&& (neobundle#is_installed('vimproc.vim') || !executable('clang'))"""

[[plugins]]
repository = 'scrooloose/nerdtree'

  [plugins.commands]
  name = [
    'NERDTree', 'NERDTreeCWD', 'NERDTreeClose', 'NERDTreeFind', 'NERDTreeFocus',
    'NERDTreeFromBookmark', 'NERDTreeMirror', 'NERDTreeToggle',
  ]
  complete = 'dir'

[[plugins]]
repository = 'thinca/vim-ambicmd'
mappings = ':'

