[[plugins]]
repository = 'Align'
commands = ['Align', 'AlignCtrl']
mappings = '<Plug>AM_'

[[plugins]]
repository = 'airblade/vim-rooter'
mappings = '<Plug>RooterChangeToRootDirectory'

[[plugins]]
repository = 'ahayman/vim-nodejs-complete'
filetypes = 'javascript'

[[plugins]]
repository = 'c9s/perlomni.vim'
filetypes = 'perl'

[[plugins]]
repository = 'cespare/vim-toml'
filename_patterns = '\.toml$'

[[plugins]]
repository = 'davidhalter/jedi-vim'
filetypes = 'python'
depends = 'davidhalter/jedi'

[[plugins]]
repository = 'dbext.vim'

[[plugins]]
repository = 'fatih/vim-go'
filetypes = 'go'

[[plugins]]
repository = 'flazz/vim-colorschemes'
gui = 1

[[plugins]]
repository = 'gcmt/wildfire.vim'
mappings = ['<Plug>(wildfire-water)', '<Plug>(wildfire-fuel)']

[[plugins]]
repository = 'godlygeek/tabular'
commands = ['Tab', 'Tabularize']

[[plugins]]
repository = 'haya14busa/incsearch.vim'
mappings = [
  '<Plug>(incsearch-forward)',
  '<Plug>(incsearch-backward)',
  '<Plug>(incsearch-stay)',
  '<Plug>(incsearch-nohl-n)',
  '<Plug>(incsearch-nohl-N)',
  '<Plug>(incsearch-nohl-*)',
  '<Plug>(incsearch-nohl-#)',
  '<Plug>(incsearch-nohl-g*)',
  '<Plug>(incsearch-nohl-g#)',
]
disabled = '&filetype == "man" && has("macunix")'

[[plugins]]
repository = 'hotchpotch/perldoc-vim'
filetypes = 'perl'
commands = 'Perldoc'

[[plugins]]
repository = 'artur-shaik/vim-javacomplete2'
filetypes = 'java'
disabled = 'filereadable(expand("~/.eclim/.eclimd_instances"))'

[[plugins]]
repository = 'jceb/vim-hier'
gui = 1

[[plugins]]
repository = 'justinmk/vim-sneak'
depends = 'tpope/vim-repeat'
mappings = ['s', 'S']

[[plugins]]
repository = 'justmao945/vim-clang'
filetypes = ['c', 'cpp']
# Ideally neobundle#is_installed('vim-marching'), but not due to the parsing.
# See vim-clang section in .vimrc for more details.
disabled = """
!exists('g:use_vim_clang') || !g:use_vim_clang \
&& (neobundle#is_installed('vimproc.vim') || !executable('clang'))"""

[[plugins]]
repository = 'kana/vim-altr'
filetypes = ['c', 'cpp']
mappings = ['<Plug>(altr-forward)', '<Plug>(altr-back)']

[[plugins]]
repository = 'kana/vim-niceblock'
mappings = [
  ['x', '<Plug>(niceblock-I)'],
  ['x', '<Plug>(niceblock-A)'],
]

[[plugins]]
repository = 'kana/vim-smartchr'
filetypes = 'cpp'

[[plugins]]
repository = 'kana/vim-textobj-user'

[[plugins]]
repository = 'kannokanno/previm'
commands = 'PrevimOpen'
filetypes = 'markdown'
depends = 'tyru/open-browser.vim'

[[plugins]]
repository = 'lambdalisue/vim-gista'
commands = 'Gista'
unite_sources = 'gista'

[[plugins]]
repository = 'lervag/vim-latex'
filetypes = 'tex'

[[plugins]]
#repository = 'marcus/rsense'
repository = 'NigoroJr/rsense'
filetypes = 'ruby'
# When vim-monster can be used
disabled = """
executable('rct-complete') \
&& (!exists('g:use_rsense') || !g:use_rsense)"""

[[plugins]]
repository = 'mattn/disableitalic-vim'
commands = 'DisableItalic'
gui = 1

[[plugins]]
repository = 'mattn/gist-vim'
commands = 'Gist'
depends = 'mattn/webapi-vim'

[[plugins]]
repository = 'mattn/webapi-vim'

[[plugins]]
repository = 'mattn/quickrunex-vim'
depends = 'thinca/vim-quickrun'

[[plugins]]
repository = 'mips.vim'
filetypes = 'asm'

[[plugins]]
repository = 'NigoroJr/foofile.vim'

  [plugins.commands]
  name = 'FooFile'
  complete = 'customlist,foofile#complete'

  [plugins.commands]
  name = 'FooFileLast'
  complete = 'customlist,foofile#complete'

  [plugins.commands]
  name = 'FooFileDelete'
  complete = 'customlist,foofile#complete'

  [plugins.commands]
  name = 'FooFileSaveAs'
  complete = 'file'

[[plugins]]
repository = 'NigoroJr/unite-matcher-hide-hidden-directories'
depends = 'Shougo/unite.vim'
on_source = 'unite.vim'

[[plugins]]
repository = 'ntpeters/vim-better-whitespace'
insert = 1
focus = 1

[[plugins]]
repository = 'osyo-manga/shabadou.vim'
depends = 'thinca/vim-quickrun'

[[plugins]]
repository = 'osyo-manga/unite-boost-online-doc'
filetypes = 'cpp'
depends = [
  'Shougo/unite.vim',
  'tyru/open-browser.vim',
  'mattn/webapi-vim',
]

[[plugins]]
repository = 'osyo-manga/unite-quickfix'
depends = 'Shougo/unite.vim'

[[plugins]]
repository = 'osyo-manga/vim-jplus'
mappings = [
  '<Plug>(jplus)', '<Plug>(jplus-getchar)', '<Plug>(jplus-input)',
  '<Plug>(jplus-getchar-with-space)', '<Plug>(jplus-input-with-space)',
]

[[plugins]]
repository = 'osyo-manga/vim-marching'
depends = [
  'Shougo/neocomplete.vim',
  'Shougo/vimproc.vim',
  'osyo-manga/vim-reunions',
]
filetypes = ['c', 'cpp']
commands = 'MarchingBufferClearCache'
mappings = [
  ['i', '<Plug>(marching_force_start_omni_complete)']
]
disabled = """
(exists('g:use_vim_clang') && g:use_vim_clang) \
|| !executable('clang')"""

[[plugins]]
repository = 'osyo-manga/vim-monster'
filetypes = 'ruby'
depends = 'Shougo/vimproc.vim'
disabled = """
!executable('rct-complete') \
|| (exists('g:use_monster') && !g:use_monster) \
|| (exists('g:use_rsense') && g:use_rsense)"""

[[plugins]]
repository = 'osyo-manga/vim-precious'
filetypes = ['html', 'xhtml', 'markdown']
commands = [
  'PreciousSwitch',
  'PreciousSetContextLocal',
  'PreciousReset',
]
depends = [
  'Shougo/context_filetype.vim',
  'vim-textobj-user',
  'thinca/vim-quickrun',
]

[[plugins]]
repository = 'osyo-manga/vim-snowdrop'
filetypes = 'cpp'
commands = [
  'SnowdropClearLogs',
  'SnowdropEchoClangVersion',
  'SnowdropLogs',
  'SnowdropVerify',
]
disabled = '!filereadable(expand("~/.eclim/.eclimd_instances"))'

[[plugins]]
repository = 'osyo-manga/vim-stargate'
commands = 'StargateInclude'
filetypes = 'cpp'

[[plugins]]
repository = 'osyo-manga/vim-watchdogs'
filetypes = ['c', 'cpp']
depends = ['jceb/vim-hier', 'thinca/vim-quickrun']
gui = 1

  [plugins.commands]
  name = ['WatchdogsRun', 'WatchdogsRunSilent']
  complete = 'customlist,quickrun#complete'

[[plugins]]
repository = 'rhysd/accelerated-jk'
mappings = [
  '<Plug>(accelerated_jk_gj)', '<Plug>(accelerated_jk_gk)',
  '<Plug>(accelerated_jk_gj_position', '<Plug>(accelerated_jk_gk_position)'
  '<Plug>(accelerated_jk_j)', '<Plug>(accelerated_jk_k)',
  '<Plug>(accelerated_jk_j_position', '<Plug>(accelerated_jk_k_position)'
]

[[plugins]]
repository = 'rhysd/clever-f.vim'
mappings = ['f', 'F', 't', 'T']

[[plugins]]
repository = 'rhysd/vim-go-impl'
filetypes = 'go'

[[plugins]]
repository = 'rhysd/wandbox-vim'
commands = ['Wandbox', 'WandboxAsync']
depends = ['thinca/vim-quickrun', 'Shougo/vimproc.vim']

[[plugins]]
repository = 'scrooloose/nerdtree'
commands = 'NERDTreeFind'

  [plugins.commands]
  name = 'NERDTree'
  complete = 'dir'

[[plugins]]
repository = 'Shougo/context_filetype.vim'

[[plugins]]
repository = 'Shougo/neocomplcache-rsense.vim'
depends = ['Shougo/neocomplcache.vim', 'rsense']
on_source = 'rsense'
disabled = 'NeoCompleteCompatible()'

[[plugins]]
# Has autoload.insert in .vimrc
repository = 'Shougo/neocomplcache.vim'
depends = 'Shougo/vimproc.vim'
disabled = 'NeoCompleteCompatible()'

[[plugins]]
# Has autoload.insert in .vimrc
repository = 'Shougo/neocomplete.vim'
depends = 'Shougo/vimproc.vim'
disabled = '!NeoCompleteCompatible()'

[[plugins]]
repository = 'Shougo/neomru.vim'
depends = 'Shougo/unite.vim'
on_source = 'unite.vim'

[[plugins]]
repository = 'Shougo/neosnippet-snippets'
on_source = 'neosnippet.vim'
depends = 'Shougo/neosnippet.vim'

[[plugins]]
repository = 'Shougo/neosnippet.vim'
on_source = ['neocomplcache.vim', 'neocomplete.vim']
commands = 'NeoSnippetEdit'

[[plugins]]
repository = 'Shougo/unite-outline'
depends = 'Shougo/unite.vim'

[[plugins]]
repository = 'Shougo/unite.vim'
depends = 'Shougo/vimproc.vim'

  [plugins.commands]
  name = [
    'Unite',
    'UniteWithBufferDir',
    'UniteWithCurrentDir',
    'UniteWithProjectDir',
    'UniteWithInputDirectory',
    'UniteWithCursorWord',
  ]
  complete = 'customlist,unite#complete#source'

[[plugins]]
repository = 'Shougo/vimfiler.vim'
explorer = 1

  [plugins.commands]
  name = [
    'VimFiler',
    'VimFilerCurrentDir',
    'VimFilerBufferDir',
    'VimFilerExplorer',
  ]
  complete = 'customlist,vimfiler#complete'

[[plugins]]
repository = 'Shougo/vimshell.vim'
depends = 'Shougo/vimproc.vim'

  [plugins.commands]
  name = [
    'VimShell',
    'VimShellBufferDir',
    'VimShellCreate',
    'VimShellTab',
    'VimShellPop',
    'VimShellCurrentDir',
    'VimShellExecute',
    'VimShellInteractive',
    'VimShellTerminal',
    'VimShellSendString',
    'VimShellSendBuffer',
  ]
  complete = 'customlist,vimshell#complete'

[[plugins]]
repository = 'Shougo/vinarise.vim'
vim_version = '7.3'

  [plugins.commands]
  name = 'Vinarise'
  complete = 'file'

[[plugins]]
repository = 'starcraftman/vim-eclim'
filetypes = 'java'
disabled = '!filereadable(expand("~/.eclim/.eclimd_instances"))'

[[plugins]]
repository = 'sudo.vim'
commands = ['SudoRead', 'SudoWrite']

[[plugins]]
repository = 'supermomonga/neocomplete-rsense.vim'
depends = ['Shougo/neocomplete.vim', 'rsense']
on_source = 'rsense'
disabled = '!NeoCompleteCompatible()'

[[plugins]]
repository = 'supermomonga/unite-kawaii-calc'
depends = 'Shougo/unite.vim'

[[plugins]]
repository = 'TextFormat'
commands = ['AlignCenter', 'AlignJustify', 'AlignRight', 'AlignLeft']

[[plugins]]
repository = 'thinca/vim-ambicmd'
mappings = ':'

[[plugins]]
repository = 'thinca/vim-prettyprint'

  [plugins.commands]
  name = ['PrettyPrint', 'PP']
  complete = 'expression'

[[plugins]]
repository = 'thinca/vim-quickrun'
depends = 'Shougo/vimproc.vim'
mappings = '<Plug>(quickrun)'

  [plugins.commands]
  name = 'QuickRun'
  complete = 'customlist,quickrun#complete'

[[plugins]]
repository = 'thinca/vim-ref'
mappings = '<Plug>(ref-keyword)'
unite_sources = 'ref'

  [plugins.commands]
  name = 'Ref'
  complete = 'customlist,ref#complete'

[[plugins]]
repository = 'tkztmk/vim-vala'
filename_patterns = '\.vala$'

[[plugins]]
repository = 'tomtom/tcomment_vim'
mappings = [
  'gc', 'g<', 'g>',
  '<Plug>TComment_',
]

[[plugins]]
repository = 'tpope/vim-abolish'
depends = 'tpope/vim-repeat'
commands = ['Abolish', 'Subvert', 'S']
mappings = 'cr'

[[plugins]]
repository = 'tpope/vim-bundler'
filetypes = 'ruby'
commands = 'Bundle'
filename_patterns = 'Gemfile\.lock'

[[plugins]]
repository = 'tpope/vim-endwise'
filetypes = [
  'aspvbs', 'c', 'cpp', 'crystal', 'elixir', 'htmldjango', 'lua', 'matlab',
  'objc', 'ruby', 'sh', 'snippets', 'vb', 'vbnet', 'vim', 'xdefaults', 'zsh',
]

[[plugins]]
repository = 'tpope/vim-fugitive'
augroup = 'fugitive'
commands = [
  'Git', 'Git!', 'Gcd', 'Glcd', 'Gstatus', 'Gcommit', 'Gmerge', 'Gpull',
  'Gpush', 'Gfetch', 'Ggrep', 'Glgrep', 'Glog', 'Gllog', 'Gedit', 'Gsplit',
  'Gvsplit', 'Gtabedit', 'Gpedit', 'Gsplit!', 'Gvsplit!', 'Gtabedit!',
  'Gpedit!', 'Gread', 'Gread!', 'Gwrite', 'Gwrite', 'Gwq', 'Gwq!', 'Gdiff',
  'Gsdiff', 'Gvdiff', 'Gmove', 'Gremove', 'Gblame',
]

[[plugins]]
repository = 'tpope/vim-markdown'
depends = 'godlygeek/tabular'
filetypes = 'markdown'

[[plugins]]
repository = 'tpope/vim-rails'
filetypes = ['ruby', 'eruby', 'css', 'scss', 'html', 'javascript', 'yaml']

[[plugins]]
repository = 'tpope/vim-rake'
filetypes = 'ruby'

[[plugins]]
repository = 'tpope/vim-rbenv'
filetypes = 'ruby'
commands = 'Rbenv'

[[plugins]]
repository = 'tpope/vim-repeat'
mappings = '.'
functions = 'repeat#set'

[[plugins]]
repository = 'tpope/vim-speeddating'
depends = 'tpope/vim-repeat'
mappings = ['<C-a>', '<C-x>']

[[plugins]]
repository = 'tpope/vim-surround'
depends = 'tpope/vim-repeat'
mappings = ['<Plug>Ysurround', '<Plug>Dsurround', '<Plug>Csurround']

[[plugins]]
repository = 'tsukkee/unite-help'
depends = 'Shougo/unite.vim'

[[plugins]]
repository = 'tyru/open-browser.vim'
commands = 'OpenBrowser'

[[plugins]]
repository = 'tyru/restart.vim'
commands = ['Restart', 'Restart!']
gui = 1

[[plugins]]
repository = 'wesQ3/vim-windowswap'
functions = [
  'WindowSwap#MarkWindowSwap',
  'WindowSwap#DoWindowSwap',
  'WindowSwap#EasyWindowSwap',
]
