" gentooish
" jellybeans
" moria
if neobundle#is_installed('color_coded-colorschemes')
  let s:colorscheme = 'molokaied'
else
  let s:colorscheme = 'molokai'
endif
execute 'colorscheme' s:colorscheme

if exists(':DisableItalic') == 2
  DisableItalic
endif

if has('gui_running')
  " Font for programming
  if has('gui_mac') || has('gui_macvim')
    set guifont=Ricty\ Discord:h16
  elseif has('gui_gtk')
    set guifont=Ricty\ Discord\ 9
  elseif has('gui_win32')
    set guifont=Ricty\ 13
  endif

  set guioptions-=m " Hide menubar
  set guioptions-=T " Hide toolbar
  set guioptions-=r " Hide right scrollbar
  set guioptions-=L " Hide left scrollbar

  set iminsert=2
endif

if filereadable(expand('~/.localrc/gvimrc'))
  source ~/.localrc/gvimrc
end
