# securemodelines
[[plugins]]
repository = 'ciaranm/securemodelines'

# neobundle.vim
[[plugins]]
repository = 'Shougo/neobundle.vim'
depends = 'Shougo/vimproc.vim'
fetch = 1

# previm
[[plugins]]
repository = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
on_ft = 'markdown'
depends = 'tyru/open-browser.vim'

# vimproc.vim
[[plugins]]
repository = 'Shougo/vimproc.vim'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin = 'make -f make_cygwin.mak'
  mac = 'make -f make_mac.mak'
  unix = 'make -f make_unix.mak'

# vim-obsession
[[plugins]]
repository = 'tpope/vim-obsession'
commands = ['Obsession', 'Obsession!']
