# color_coded
[[plugins]]
repository = 'jeaye/color_coded'
on_ft = ['c', 'cpp', 'objc', 'objcpp']
build = 'cmake . && make && make install && make clean && make clean_clang'
build_commands = ['cmake', 'make']
vim_version = '7.4.330'
disabled = """
!has('lua') || (exists('g:disable_color_coded') && g:disable_color_coded)"""
gui = 1

# vim-altr
[[plugins]]
repository = 'kana/vim-altr'
on_ft = ['c', 'cpp']
on_map = ['<Plug>(altr-forward)', '<Plug>(altr-back)']

# vim-cpp-enhanced-highlight
[[plugins]]
repository = 'octol/vim-cpp-enhanced-highlight'
on_ft = 'cpp'
terminal = 1

# vim-marching
[[plugins]]
repository = 'osyo-manga/vim-marching'
depends = [
  'Shougo/neocomplete.vim',
  'Shougo/vimproc.vim',
  'osyo-manga/vim-reunions',
]
on_ft = ['c', 'cpp']
on_cmd = 'MarchingBufferClearCache'
on_map = [
  ['i', '<Plug>(marching_force_start_omni_complete)'],
]
disabled = """
(exists('g:use_vim_clang') && g:use_vim_clang) \
|| !executable('clang')"""

# vim-snowdrop
[[plugins]]
repository = 'osyo-manga/vim-snowdrop'
on_ft = 'cpp'
on_cmd = [
  'SnowdropClearLogs',
  'SnowdropEchoClangVersion',
  'SnowdropLogs',
  'SnowdropVerify',
]

# vim-stargate
[[plugins]]
repository = 'osyo-manga/vim-stargate'
on_cmd = 'StargateInclude'
on_ft = 'cpp'

# vim-watchdogs
[[plugins]]
repository = 'osyo-manga/vim-watchdogs'
on_ft = ['c', 'cpp']
depends = ['jceb/vim-hier', 'thinca/vim-quickrun']
gui = 1

  [plugins.on_cmd]
  name = ['WatchdogsRun', 'WatchdogsRunSilent']
  complete = 'customlist,quickrun#complete'
