# neocomplete.vim
[[plugins]]
repository = 'Shougo/neocomplete.vim'
depends = ['Shougo/vimproc.vim', 'Shougo/context_filetype.vim']
disabled = '!has("lua")'
vim_version = '7.3.885'
on_i = 1

# vim-javacomplete2
[[plugins]]
repository = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'
disabled = '!executable("mvn") || !has("python")'
vim_version = '7.4.0'
