# shabadou.vim
[[plugins]]
repository = 'osyo-manga/shabadou.vim'
depends = 'thinca/vim-quickrun'
on_source = 'vim-quickrun'

# vim-quickrun
[[plugins]]
repository = 'thinca/vim-quickrun'
depends = 'Shougo/vimproc.vim'
on_map = '<Plug>(quickrun)'

  [plugins.on_cmd]
  name = 'QuickRun'
  complete = 'customlist,quickrun#complete'

# wandbox-vim
[[plugins]]
repository = 'rhysd/wandbox-vim'
on_cmd = ['Wandbox', 'WandboxAsync']
depends = ['thinca/vim-quickrun', 'Shougo/vimproc.vim']

# quickrunex-vim
[[plugins]]
repository = 'mattn/quickrunex-vim'
depends = 'thinca/vim-quickrun'
on_source = 'vim-quickrun'
