#!/bin/sh

# Update PATH so that dmenu can see stuff in ~/bin
export PATH="$HOME/bin:$PATH"

# Input Method setup
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

# Start ibus daemon
ibus-daemon -dx

# TODO: Automatically find primary monitor
xrandr --output DP-0 --mode 3840x2160

# Customizing mouse
if hash xbindkeys 2>/dev/null; then
    xbindkeys --poll-rc
fi

# Set cursor to pointer
xsetroot -cursor_name left_ptr

# Disable screensaver
xset s off
xset -dpms
setterm -blank 0 -powerdown 0

# Run any local configurations (such as setting wallpaper)
if [ -f ~/.localrc/xsession ]; then
    sh ~/.localrc/xsession
fi

exec xmonad
