alias r="ros2"
alias rr="ros2 run"
alias rb="ros2 bag"
alias rl="ros2 launch"
alias rte="ros2 topic echo"
alias rtl="ros2 topic list"
alias rti="ros2 topic info"
alias rth="ros2 topic hz"
alias rnl="ros2 node list"
alias rni="ros2 node info"
alias rpf="ros2 pkg prefix"
alias rsu="[[ -e install/setup.zsh ]] && source install/setup.zsh"

alias rpg="rqt_graph"
# alias rtt="rosrun rqt_tf_tree rqt_tf_tree"
