autoload -Uz colors && colors

export LANG="en_US.UTF-8"
export LC_ALL="$LANG"
export LANGUAGE="$LANG"
if [ -d $HOME/src/go ]; then
    export GOPATH=$HOME/src/go
fi

if [[ -d $HOME/usr/lib ]]; then
    export LD_LIBRARY_PATH="$HOME/usr/lib:$LD_LIBRARY_PATH"
fi

if (( $+commands[nvim] )); then
    export EDITOR="nvim"
else
    export EDITOR="vim"
fi
if hash vimmanpager 2>/dev/null; then
    export MANPAGER=vimmanpager
fi
export ALTERNATE_EDITOR=""

path=($HOME/bin(N) \
    $HOME/usr/bin(N) \
    $HOME/.local/bin(N) \
    /usr/local/bin(N) \
    /usr/bin(N) \
    /bin(N) \
    /usr/sbin(N) \
    /sbin(N) \
    $path)
typeset -U path
fpath=($HOME/.zsh/functions(N) \
    $fpath)
typeset -U fpath
manpath=(
    $HOME/usr/share/man(N) \
    $manpath)
typeset -U manpath

export HISTFILE=~/.histfile
export HISTSIZE=6000000
export SAVEHIST=6000000
export WORDCHARS="*?_-.[]~=&;!#$%^(){}<>|"
# Don't trim space after completion for these chars
export ZLE_SPACE_SUFFIX_CHARS=$'|&'
# Prompt "do you wish to see all N possibilities"
# only when going out of screen
export LISTMAX=0
export REPORTTIME=10
export TIMEFMT="\
$fg_bold[blue]%J$reset_color
  %*E :: $fg[green]U$reset_color %*U :: $fg[blue]S$reset_color %*S :: %M KiB"

export XDG_DATA_HOME=$HOME/.local/share/
export XDG_CONFIG_HOME=$HOME/.config/
export XDG_DATA_DIRS=/usr/local/share/:/usr/share/
