;;;; General functions
(defun insert-newline-below ()
  (interactive)
  (next-line)
  (beginning-of-line)
  (insert "\n")
  (previous-line)
  (indent-for-tab-command))

(defun insert-newline-above ()
  (interactive)
  (beginning-of-line)
  (insert "\n")
  (previous-line)
  (indent-for-tab-command))
